# Generated by Django 5.0.4 on 2024-06-20 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBinRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='wasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='wasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('location', models.TextField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('reward_points', models.IntegerField(default=0, null=True)),
                ('bin_level', models.IntegerField(null=True)),
                ('battery_level', models.IntegerField(null=True)),
                ('charge_status', models.BooleanField(null=True)),
                ('power_consumption', models.FloatField(null=True)),
                ('battery_status', models.IntegerField(null=True)),
                ('picked_up', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_of_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wastecategory')),
            ],
        ),
        migrations.CreateModel(
            name='WastePickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('picked_up', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_picked', models.DateTimeField()),
                ('type_of_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.wastecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
